name: Testing secret variables

on:
  workflow_dispatch
  
env:
      ACTIONS_STEP_DEBUG: true

jobs:
  test_context_variables:
    runs-on: ubuntu-latest
    steps:
    - name: "Checking secrets variables"
      run: |
        echo "secrets values : ${{ secrets.MY_KEY}}"
        ${{ secrets.MY_KEY }}
  
